version: "3"

services:
  # challenge_api:
  #   container_name: challenge_api
  #   image: challenge_api
  #   build:
  #     context: ..
  #     dockerfile: cmd/api/Dockerfile
  #   restart: always
  #   depends_on:
  #     - mssql
  #   ports:
  #     - "8080:80"
  #   networks:
  #     - challeng_net
  #   environment:
  #     - DB_DRIVER=sqlserver
  #     - DB_HOST=mssql
  #     - DB_PORT=1433
  #     - DB_USER=sa
  #     - DB_PASSWORD=@docker@2022
  #     - DB_NAME=StarWarsDB
  #     - SERVER_PORT=0.0.0.0:80
  #     - STAR_WARS_API=https://swapi.dev/api
  #     - LOG_PATH=/app/logs.txt

  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    ports:
      - "1433:1433"
    networks:
      - challeng_net
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: '@docker@2022'
      MSSQL_AGENT_ENABLED: 'True'
      MSSQL_PID: "Developer"

  mssqltools:
    container_name: mssql-tools
    image: mcr.microsoft.com/mssql-tools
    networks:
      - challeng_net
    depends_on:
      - mssql
    volumes:
      - ../resources/database.sql:/tmp/database.sql
      - ../resources/init-database.sh:/tmp/init-database.sh
    command: /bin/bash ./tmp/init-database.sh

networks:
  challeng_net:
    driver: bridge
