version: "3"

services:
  challenge_api:
    container_name: challenge_api
    image: challenge_api
    build:
      context: ..
      dockerfile: cmd/api/Dockerfile
    restart: always
    ports:
      - "9000:80"
    networks:
      - challeng_net
    environment:
      - PORT=80

networks:
  challeng_net:
    driver: bridge
