name: "challenge"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  K8S_NAMESPACE: challenge
  DOCKER_USERNAME: jailtonjunior

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout GithubActions
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

    - name: "Unit Tests"
      run: go test --coverprofile tests/coverage.out ./...

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Docker Login
      uses: docker/login-action@v1.9.0
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2.4.0
      with:
        context: .
        file: cmd/api/Dockerfile
        push: true
        tags: |
          ${{ env.DOCKER_USERNAME }}/challenge_api:latest
          ${{ env.DOCKER_USERNAME }}/challenge_api:v${{ github.run_number }}

  deploy:
    needs: [build]
    runs-on: ubuntu-20.04
    environment:
      name: deploy
    steps:
    - name: Checkout GithubActions
      uses: actions/checkout@v2

    - name: Kubernetes set context
      uses: Azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.K8S_CONFIG }}

    - name: Deploy
      uses: Azure/k8s-deploy@v1.3
      with:
        namespace: ${{ env.K8S_NAMESPACE }}
        images: ${{ env.DOCKER_USERNAME }}/challenge_api:v${{ github.run_number }}
        manifests: |
          deployment/kubernetes/backend.yml
